server:
  port: 9090

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1

        - id: loan
          uri: lb://loan
          predicates:
            - Path=/loan-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
